import type { BankAccount, CreditCard, CardInvoice, Transaction } from '../types/financial';

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'acc_1',
    name: 'Nubank Conta',
    type: 'checking',
    current_balance: 14850.40,
    color: '#8A05BE',
    account_number: '0001 / 987654-3',
  },
  {
    id: 'acc_2',
    name: 'Itaú Personnalité',
    type: 'checking',
    current_balance: 32410.00,
    color: '#EC7000',
    account_number: '3802 / 12345-6',
  },
  {
    id: 'acc_3',
    name: 'XP Investimentos',
    type: 'investment',
    current_balance: 85600.00,
    color: '#000000',
    account_number: 'Cartos / 55432-1',
  },
];

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card_1',
    name: 'Nubank Ultravioleta',
    account_id: 'acc_1',
    total_limit: 25000.00,
    available_limit: 18450.00,
    closing_day: 22,
    due_day: 28,
    card_brand: 'mastercard',
    theme_color: '#8A05BE',
    last_digits: '4892',
  },
  {
    id: 'card_2',
    name: 'Itaú Visa Infinite',
    account_id: 'acc_2',
    total_limit: 45000.00,
    available_limit: 36200.00,
    closing_day: 15,
    due_day: 22,
    card_brand: 'visa',
    theme_color: '#EC7000',
    last_digits: '9012',
  },
  {
    id: 'card_3',
    name: 'XP Visa Infinite',
    account_id: 'acc_3',
    total_limit: 30000.00,
    available_limit: 27150.00,
    closing_day: 5,
    due_day: 12,
    card_brand: 'visa',
    theme_color: '#334155',
    last_digits: '1134',
  },
];

export const INITIAL_INVOICES: CardInvoice[] = [
  // Current month invoices (Sep 2026)
  {
    id: 'inv_card_1_2026_9',
    credit_card_id: 'card_1',
    month: 9,
    year: 2026,
    due_date: '2026-09-28',
    status: 'open',
    total_amount: 3250.00,
  },
  {
    id: 'inv_card_2_2026_9',
    credit_card_id: 'card_2',
    month: 9,
    year: 2026,
    due_date: '2026-09-22',
    status: 'open',
    total_amount: 4800.00,
  },
  {
    id: 'inv_card_3_2026_9',
    credit_card_id: 'card_3',
    month: 9,
    year: 2026,
    due_date: '2026-09-12',
    status: 'paid',
    total_amount: 2850.00,
  },
  // Future month invoices (Oct 2026)
  {
    id: 'inv_card_1_2026_10',
    credit_card_id: 'card_1',
    month: 10,
    year: 2026,
    due_date: '2026-10-28',
    status: 'open',
    total_amount: 2850.00,
  },
  {
    id: 'inv_card_2_2026_10',
    credit_card_id: 'card_2',
    month: 10,
    year: 2026,
    due_date: '2026-10-22',
    status: 'open',
    total_amount: 3900.00,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Incomes
  {
    id: 'tx_inc_1',
    type: 'income',
    description: 'Salário Tech Corp',
    amount: 18500.00,
    date: '2026-09-01',
    category: 'Salário',
    account_id: 'acc_2',
  },
  {
    id: 'tx_inc_2',
    type: 'income',
    description: 'Rendimentos Dividendos XP',
    amount: 2450.00,
    date: '2026-09-05',
    category: 'Investimentos',
    account_id: 'acc_3',
  },
  // Account Expenses
  {
    id: 'tx_exp_1',
    type: 'expense',
    description: 'Aluguel & Condomínio',
    amount: 4200.00,
    date: '2026-09-05',
    category: 'Moradia',
    account_id: 'acc_2',
  },
  {
    id: 'tx_exp_2',
    type: 'expense',
    description: 'Escola Filhos',
    amount: 2100.00,
    date: '2026-09-08',
    category: 'Educação',
    account_id: 'acc_1',
  },
  // Card 1 Expenses & Installments
  {
    id: 'tx_card1_1',
    type: 'expense',
    description: 'Supermercado St. Marche',
    amount: 680.40,
    date: '2026-09-03',
    category: 'Alimentação',
    credit_card_id: 'card_1',
    invoice_id: 'inv_card_1_2026_9',
  },
  {
    id: 'tx_card1_2',
    type: 'expense',
    description: 'Apple Store MacBook Air (3/10)',
    amount: 850.00,
    date: '2026-09-04',
    category: 'Compras',
    credit_card_id: 'card_1',
    invoice_id: 'inv_card_1_2026_9',
    installment_group_id: 'inst_macbook',
    installment_current: 3,
    installment_total: 10,
  },
  {
    id: 'tx_card1_3',
    type: 'expense',
    description: 'Apple Store MacBook Air (4/10)',
    amount: 850.00,
    date: '2026-10-04',
    category: 'Compras',
    credit_card_id: 'card_1',
    invoice_id: 'inv_card_1_2026_10',
    installment_group_id: 'inst_macbook',
    installment_current: 4,
    installment_total: 10,
  },
  {
    id: 'tx_card1_4',
    type: 'expense',
    description: 'Restaurante Fogo de Chão',
    amount: 420.00,
    date: '2026-09-06',
    category: 'Alimentação',
    credit_card_id: 'card_1',
    invoice_id: 'inv_card_1_2026_9',
  },
  // Card 2 Expenses & Installments
  {
    id: 'tx_card2_1',
    type: 'expense',
    description: 'Passagem Aérea Férias (2/6)',
    amount: 950.00,
    date: '2026-09-02',
    category: 'Lazer',
    credit_card_id: 'card_2',
    invoice_id: 'inv_card_2_2026_9',
    installment_group_id: 'inst_flight',
    installment_current: 2,
    installment_total: 6,
  },
  {
    id: 'tx_card2_2',
    type: 'expense',
    description: 'Passagem Aérea Férias (3/6)',
    amount: 950.00,
    date: '2026-10-02',
    category: 'Lazer',
    credit_card_id: 'card_2',
    invoice_id: 'inv_card_2_2026_10',
    installment_group_id: 'inst_flight',
    installment_current: 3,
    installment_total: 6,
  },
  {
    id: 'tx_card2_3',
    type: 'expense',
    description: 'Posto Petrobras Gasolina',
    amount: 240.00,
    date: '2026-09-05',
    category: 'Transporte',
    credit_card_id: 'card_2',
    invoice_id: 'inv_card_2_2026_9',
  },
];
